### PR TITLE
Wait#until returns result of block

### PR DESCRIPTION
**Pull request by chrismikehogan**
Addresses https://github.com/watir/watir-webdriver/issues/360

### CODE REVIEW

**Comment by p0deje** [comment]
Thanks!

**Comment by titusfortner** [comment]
If we are going to make this change (see comment in issue), I think Bret's suggestion is better.

**Comment by p0deje** [comment]
It won't work, because it doesn't care if `yield(self)` returns true or false. It just returns after the first execution.

**Comment by titusfortner** [comment]
Ah yeah, returns in blocks, that makes sense. :)

**Comment by bret** [comment]
Oh I see. Thanks.

**Comment by chrismikehogan** [comment]
Gracias, all.

When do patch cuts typically get made?

**Comment by titusfortner** [comment]
Can you reference github instead of the gem in your gemfile for the time being?

**Comment by chrismikehogan** [comment]
@titusfortner yep I'm all set locally, just curious

**Comment by chrismikehogan** [comment]
curious

**Pull request merged**
