### PR TITLE
Drop support of Ruby 1.8 and Ruby 1.9

### PR DESCRIPTION
**Pull request by p0deje**
Per conversation in #324

### CODE REVIEW

**Comment by p0deje** [comment]
@titusfortner Guess that's pretty much it, can you go over the changes and let me know if you're fine with them. I'm not particularly sure we need `%i` shorthand, but since we're using `%w`, I've decided to do the same.

**Comment by Blackbaud-TitusFortner** [comment]
Excellent work, I'm excited to be able to use 2.0 syntax. I want to run this against our suite of tests just to verify there isn't an issue that our watirspecs don't catch. I'll do that today.

**Comment by p0deje** [comment]
@Blackbaud-TitusFortner Let me know when you're done, only waiting for it to merge.

**Comment by titusfortner** [comment]
Passed all my tests, looks great. Do we need to run both 2.0 & 2.1 on Travis, or is there any down side to checking both?

**Comment by p0deje** [comment]
I think having both `2.0` and `2.1` is good while `2.0` is still supported.

**Pull request merged**
