### PR TITLE
optimize Select #include? similar to #selected?

### PR DESCRIPTION
**Pull request by Conky5**
Optimize `#include?` similar to `#selected?` for `Select`, as desired by the TODO comment.

### CODE REVIEW

**Comment by p0deje** [comment]
Thanks for a pull request!

I think the purpose of this TODO was to provide with similar to `#selected?` logic:

1. raise `UnknownObjectException` if no options present
2. check both option text and label attribute

Thus, I think the same changes should be applied.

Also, can you write a specs for all these cases. An example of such specs for `#selected?` are in [watirspec](https://github.com/watir/watirspec/blob/master/select_list_spec.rb#L217-230). Let me know if you need any help with this.

**Comment by Conky5** [comment]
Howdy @p0deje! Thanks for your response.
1. I'm not sure raising an `UnknownObjectException` makes sense for `#include?` since it is only checking if the option exists.  The existing behavior is to just return `False` if the option does not exist.  A select list without any options would just always return `False`.
2. I'll add the label attribute check and tests, the `#include?` description actually says "text or label" already https://github.com/watir/watir-webdriver/blob/master/lib/watir-webdriver/elements/select.rb#L41

**Comment by titusfortner** [comment]
The current implementation checks several times if each element is enabled, which this code doesn't do. Are select list options often disabled? And do we want to change our true/false based on that? Do we need a spec for this to verify this solution works?

Without the enabled checks, this solution makes significantly fewer wire calls and is more efficient at finding the first matching element.

I agree with @Conky5, it makes sense to raise an error if we are passing in a parameter and asking for information about it when it doesn't exist. Asking if it is included in the list should return true/false. I would see a potential test being, is it included, then check to see if it is selected so it doesn't raise the exception in the latter call.

**Comment by p0deje** [comment]
> The current implementation checks several times if each element is enabled, which this code doesn't do. Are select list options often disabled? And do we want to change our true/false based on that? Do we need a spec for this to verify this solution works?

I think it doesn't make sense to check for enabled/disabled in `#include?` because can question method is responding to is if it's included, not can be selected.

> I agree with @Conky5, it makes sense to raise an error if we are passing in a parameter and asking for information about it when it doesn't exist. Asking if it is included in the list should return true/false. I would see a potential test being, is it included, then check to see if it is selected so it doesn't raise the exception in the latter call.

Agreed, let's stick to this behavior.

**Comment by titusfortner** [comment]
Agreed. Definitely more performance boost than I expected. @Conky5 - Nice work.

**Comment by Conky5** [comment]
Thanks @titusfortner :+1:

**Pull request merged**
