### PR TITLE
differentiate Element#visible? and Element#present?

### PR DESCRIPTION
**Pull request by titusfortner**

### CODE REVIEW

**Comment by titusfortner** [comment]
This PR is a spec update only. I'm still figuring out git submodules; I might not want to be referencing a watirspec commit that isn't yet in master (The intent is for Travis CI to see and run it). Even if this works, I expect I will need to rebase it before merging.

**Comment by p0deje** [comment]
@titusfortner I believe you can just push such things on your own, we usually use pull requests for things that require discussion/review.

**Comment by titusfortner** [comment]
Hey Alex, thanks. I was using it to better understand how the process we use works with coveralls and travis ci and the watirspec submodule. I'll see about getting watirspec access as well to facilitate commits like these.

**Comment by p0deje** [comment]
I’ve added you full access to watirspec.

I also think that there is no point in having separate teams for different repos, but that’s a topic to discuss at watir-development.=

**Comment by titusfortner** [comment]
close/open to fix watirspec submodule pointing issue

**Comment by titusfortner** [comment]
trying again

**Comment by titusfortner** [comment]
Well, it won't let me reopen since I did a force push on the branch in my local repo (good to know I guess). So, I just merged it instead.

**Pull request closed without merging**
